[package]
name = "sendmail/sendmail"
version = "0.1.5"
entrypoint = "sendmail"

[[module]]
name = "sendmail"
source = "./target/wasm32-wasmer-wasi/release/sendmail.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "sendmail"
module = "sendmail"
runner = "wasi"
