name: PR Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust via rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.90 --profile minimal --component rustfmt
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Check formatting
        run: cargo fmt --check

  rust-tests:
    name: Run Rust Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust via rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.90 --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Run tests
        run: cargo test

  rust-linting:
    name: Run Rust Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust via rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.90 --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Run linting
        run: cargo clippy -- -D clippy::all
